# Generated by Django 5.1.2 on 2024-10-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_id_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('Manager', 'Manager'), ('Backend Developer', 'Backend Developer'), ('Frontend Developer', 'Frontend Developer')], max_length=50),
        ),
    ]
